name: ASP.NET Framework CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Visual Studio 2019 Build Tools
      run: choco install visualstudio2019buildtools --package-parameters "--allWorkloads --includeRecommended --includeOptional" -y

      
    - name: version.
      run: |
        cd "C:\Program Files (x86)\MSBuild"
        dir


  
