name: ASP.NET Framework CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2

    
      - name: folder
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio"
          dir
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: msbuild Demo_GitHub -t:rebuild -verbosity:diag -property:Configuration=Release
        

  
