name: ASP.NET Framework CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Restore dependencies
      run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
          dir
        

  
