name: ASP.NET Framework CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '16.4'
        vs-prerelease: true
        
    - name: Find MSBuild 16.x
      id: msbuild
      run: |
        $msbuildPath = &"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -products * -requires Microsoft.Component.MSBuild -version '[16.0,17.0)' -property installationPath -latest
        echo "##[set-output name=msbuild16;]$msbuildPath"
      

    - name: Check MSBuild version
      run: msbuild -version

    - name: Build
      run: msbuild Demo_GitHub /p:Configuration=Release

  
