name: ASP.NET Framework CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Verify .NET Framework Installation
      run: |
        $installed = Get-ChildItem "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1"
        if ($installed -eq $null) { 
            Write-Host ".NET Framework 4.5.1 Developer Pack installation failed."
            exit 1 
        } else { 
            Write-Host ".NET Framework 4.5.1 Developer Pack installed successfully."
            exit 0 
        }

    - name: Setup .NET 
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '5.0.x' # your version is using.

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: msbuild Demo_GitHub -t:rebuild -verbosity:diag -property:Configuration=Release

  
