name: ASP.NET Framework CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-version: '17.0'
      
    - name: version.
      run: |
        cd "C:\Program Files (x86)\MSBuild"
        dir
    - name: Build with MSBuild
      run: |
        C:\\Program Files (x86)\\MSBuild\\15.0\\Bin\\msbuild.exe Demo_GitHub  /p:Configuration=Release

  
