name: ASP.NET Framework CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '16.0'
    - name: Install Visual Studio Build Tools 2019
      run: |
        choco install visualstudio2019buildtools --package-parameters "--allWorkloads --includeRecommended --includeOptional" -y

     
    - name: List all MSBuild installations
      run: |
        $msbuildPaths = &"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -products * -requires Microsoft.Component.MSBuild -property installationPath -all
        foreach ($path in $msbuildPaths) {
          Write-Host "Found MSBuild at $path"
        }

  
