name: ASP.NET Framework CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force;
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore 
    
    - name: Build
      run: msbuild Demo_GitHub -t:rebuild -verbosity:diag -property:Configuration=Release

    - name: Run tests
      run: vstest.console.exe "Demo_GitHub\Demo_GitHub.dll" /Platform:x64 /Framework:.NETFramework,Version=v4.5
        

  
