name: ASP.NET Framework CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '16.0'
     

    - name: Check MSBuild version
      run: msbuild -version

    - name: Build
      run: msbuild Demo_GitHub -t:rebuild -verbosity:diag -property:Configuration=Release

  
