name: ASP.NET Framework CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    
    - name: Install Visual Studio 2019 Build Tools
      run: |
        Invoke-WebRequest -Uri https://aka.ms/vs/16/release/vs_buildtools.exe -OutFile vs_buildtools.exe
        Start-Process -FilePath .\vs_buildtools.exe -ArgumentList '--quiet --norestart --wait --includeRecommended --includeOptional' -NoNewWindow -Wait

     


  
