name: ASP.NET Framework CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
   
    - name: Checkout code
      run: |
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\<Edition>\Common7\IDE\PublicAssemblies"
        dir
        

  
