name: ASP.NET Framework CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '16.4'
        vs-prerelease: true
      

    - name: Check MSBuild version
      run: msbuild -version

    - name: Build
      run: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\MSBuild\\Current\\Bin\\MSBuild.exe Demo_GitHub.sln /p:Configuration=Release"

  
